Slightly better scripts

diff --git a/scripts/module.sh.in b/scripts/module.sh.in
--- a/scripts/module.sh.in
+++ b/scripts/module.sh.in
@@ -5,28 +5,33 @@
 #PBS -l naccesspolicy=shared
 
 : ${MCANDOCK_MOD_PATH:=$([[ $PBS_ENVIRONMENT == PBS_BATCH ]] \
-	&& echo @CMAKE_INSTALL_PREFIX@/modules/@CANDOCK_VERSION@ \
-	|| echo $( cd $( dirname ${BASH_SOURCE[0]} ) && pwd ) )}
+        && echo @CMAKE_INSTALL_PREFIX@/modules/@CANDOCK_VERSION@ \
+        || echo $( cd $( dirname ${BASH_SOURCE[0]} ) && pwd ) )}
 
 # Only used if submitted to torque
 : ${module_to_run:=$PBS_JOBNAME}
+
+__sub_program=$(basename $(basename $0 .sh) )
+
+if [[ $PBS_ENVIRONMENT == PBS_BATCH ]]
+then
+        __sub_program=$(basename $module_to_run .sh)
+        MCANDOCK_NCPU=`cat $PBS_NODEFILE | egrep -v '^#'\|'^$' | wc -l | awk '{print $1}'`
+fi
 
 echo "Using modules in $MCANDOCK_MOD_PATH"
 
 if [[ ! -s $MCANDOCK_MOD_PATH/load_variables.sh ]]
 then
-	echo "Modules not found in \$MCANDOCK_MOD_PATH!"
-	echo "Please set this variable!"
-	exit 1
+        echo "Modules not found in \$MCANDOCK_MOD_PATH!"
+        echo "Please set this variable!"
+        exit 1
 fi
 
 source $MCANDOCK_MOD_PATH/load_variables.sh
 
-if [[ $PBS_ENVIRONMENT == PBS_BATCH ]]
-then
-	$(basename $module_to_run .sh)
-else
-	$(basename $(basename $0 .sh) )
-fi
+SECONDS=0
 
-echo "All caclulations for $(basename $0) are complete"
+$MCANDOCK_PATH/bin/$MCANDOCK_VER/cd_${__sub_program} --ncpu ${MCANDOCK_NCPU}
+
+echo "All caclulations for ${__sub_program} are complete taking $SECONDS to complete"
